/**
 * Real isolated SQL/COBOL/HTTP/K-means/3270 tests; no active customer or catalog data is written outside
 * fresh test databases.
 */
package com.lending.engine;
import com.lending.engine.simulation.application.*;
import com.lending.engine.simulation.infrastructure.*;
import com.lending.engine.simulation.domain.*;
import com.lending.engine.simulation.domain.Simulation.*;
import com.lending.engine.simulation.domain.BusinessRules.*;
import com.lending.engine.domain.Model.*;
import com.lending.engine.bureau.domain.Bureau.*;
import com.lending.engine.infrastructure.*;
import com.lending.engine.application.*;
import com.lending.engine.marketing.application.MarketingEngine;
import com.lending.engine.marketing.infrastructure.CobolMarketingQualifier;
import com.lending.engine.marketing.domain.Marketing.*;
import com.lending.engine.simulation.domain.Simulation.Run;
import com.lending.engine.simulation.domain.Simulation.RunRequest;
import com.lending.engine.simulation.domain.Simulation.Population;
import com.lending.engine.terminal.*;
import com.lending.engine.api.ApiServer;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.net.*;
import java.io.*;
import java.time.*;
import java.util.*;
import java.math.BigDecimal;

/**
 * Real isolated SQL/COBOL/HTTP/K-means/3270 tests; no active customer or catalog data is written outside
 * fresh test databases.
 */
@Timeout(180)
class BusinessSimulationTest {
    @TempDir Path temp;static URLClassLoader loader;static AutoCloseable analyzer;static int analysisPort;
    static final Path ROOT=Path.of("..").toAbsolutePath().normalize();static final Clock CLOCK=Clock.fixed(Instant.parse("2026-09-18T12:00:00Z"),ZoneOffset.UTC);
    SqlStore active;CustomerEngine customers;MarketingEngine marketing;SimulationEngine engine;
    /** Starts the local analysis service used by the simulation tests. */
    @BeforeAll static void analysis()throws Exception{Path jar=ROOT.resolve("marketing-service/target/marketing-offers-1.0.0.jar");loader=new URLClassLoader(new URL[]{jar.toUri().toURL()},ClassLoader.getPlatformClassLoader());var type=loader.loadClass("com.lending.offers.api.OfferServer");var instance=type.getConstructors()[0].newInstance(null,null,0,"test-analysis");type.getMethod("start").invoke(instance);analysisPort=(int)type.getMethod("port").invoke(instance);analyzer=(AutoCloseable)instance;}
    /** Stops the analysis service created for the simulation tests. */
    @AfterAll static void stopAnalysis()throws Exception{if(analyzer!=null)analyzer.close();if(loader!=null)loader.close();}
    /** Creates isolated test resources and wires the workflow under test. */
    @BeforeEach void setup(){active=new SqlStore("jdbc:h2:mem:"+UUID.randomUUID());customers=new CustomerEngine(active,new CobolUnderwriter(ROOT.resolve("build/liuwbatch"),temp),CLOCK);marketing=new MarketingEngine(active,new CobolMarketingQualifier(ROOT.resolve("build/limkbatch"),temp),CLOCK);marketing.published(new PublishedPolicies(new CobolBusinessPolicy(ROOT)));engine=new SimulationEngine(new SimulationStore("jdbc:h2:file:"+temp.resolve("business")),marketing,ROOT,CLOCK,SimulationEngine.httpAnalysis(analysisPort,"test-analysis"));}
    /** Closes the isolated test services, stores and processes. */
    @AfterEach void close(){if(engine!=null)engine.close();if(customers!=null)customers.close();if(active!=null)active.close();}
    /** Builds a modified fixture for exercising version and eligibility changes. */
    static Stage change(Stage stage,String field,Object value){var n=(com.fasterxml.jackson.databind.node.ObjectNode)Json.MAPPER.valueToTree(stage);n.set(field,Json.MAPPER.valueToTree(value));return Json.MAPPER.convertValue(n,Stage.class);}
    /** Builds customer input that satisfies the baseline demonstration policy. */
    CustomerInput good(){return EngineTest.change(EngineTest.change(EngineTest.good(),"marketingOptIn",true),"externalReference",null);}
    /** Creates the synthetic population used by this test. */
    String population(int size){return Json.MAPPER.valueToTree(engine.generate(new Generate(size,20260918))).path("id").asText();}
    /** Builds the candidate offer or execution package used by the test. */
    Draft draft(){return engine.create(new CreateDraft("Fit experiment","DEMO-PL-1","DEMO-PL"));}
    /** Runs the prepared scenario and waits for its test result. */
    Run run(Draft draft,String population)throws Exception{var r=engine.submit(new RunRequest(draft.id(),draft.version(),population,1717));long end=System.nanoTime()+java.util.concurrent.TimeUnit.SECONDS.toNanos(120);do{Thread.sleep(30);r=engine.store.get("RUN",r.id(),0,Run.class);}while(Set.of("QUEUED","RUNNING").contains(r.status())&&System.nanoTime()<end);assertEquals("COMPLETED",r.status(),r.error());return r;}
    /** Verifies that ten thousand comparison is reproducible and does not pollute active pipeline. */
    @Test void tenThousandComparisonIsReproducibleAndDoesNotPolluteActivePipeline()throws Exception{String id=population(10000);var p=engine.store.get("POPULATION",id,0,Population.class);assertEquals(10000,p.people().size());assertTrue(p.people().stream().anyMatch(Person::suppressed));var d=draft();long start=System.nanoTime();var first=run(d,id);var second=run(d,id);assertEquals(first.report(),second.report());assertEquals(10000,first.report().path("overall").path("population").asInt());assertEquals(2000,first.report().path("heldOutTest").path("population").asInt());assertEquals(0,first.report().path("overall").path("newlyEligible").asInt());assertEquals(0,first.report().path("overall").path("lostEligibility").asInt());assertTrue(first.report().path("overall").path("baseline").path("eligible").asInt()>0);assertEquals(0,customers.list(null,0,20).total());assertTrue(customers.jobs().isEmpty());assertTrue(active.read(s->s.pendingPipelines(Long.MAX_VALUE,100)).isEmpty());assertEquals(0,marketing.runs(0,20).total());assertEquals(6,marketing.offers().size());assertTrue(engine.store.rows(first.id(),9999,10).size()==1);assertTrue(first.report().path("modelArtifact").path("features").toString().contains("debtToIncome"));System.out.printf(Locale.ROOT,"Business: two reproducible 10000-customer comparisons, actual HTTP/K-means/COBOL, %.2fs; zero active customers%n",(System.nanoTime()-start)/1e9);}
    /** Verifies that forms are versioned and publishing requires reviewed current evidence. */
    @Test void formsAreVersionedAndPublishingRequiresReviewedCurrentEvidence()throws Exception{var d=draft();var rs=d.rules();var less=new RuleSet(rs.id(),rs.version(),rs.createdAt(),change(rs.underwriting(),"minimumScore",610),change(rs.marketing(),"minimumTenureMonths",6),change(rs.bureau(),"minimumScore",650));var offer=d.offer();var revised=engine.edit(d.id(),new EditDraft(1,d.name(),new OfferInput("Higher APR test",offer.product(),true,offer.startsOn(),offer.endsOn(),offer.minimumAmountUsd(),offer.maximumAmountUsd(),new BigDecimal("30"),offer.annualFeeUsd(),offer.termMonths()),less));assertEquals(2,revised.rules().version());assertEquals(660,engine.store.get("DRAFT",d.id(),1,Draft.class).rules().underwriting().minimumScore());assertEquals(409,assertThrows(Problem.class,()->engine.edit(d.id(),new EditDraft(1,d.name(),d.offer(),d.rules()))).status);var result=run(revised,population(600));assertThrows(Problem.class,()->engine.publish(result.id(),new Review("I reviewed this comparison",false)));var review=new Review("Reviewed coverage losses, costs and simulated fit; publish for local testing",true);var receipt=engine.publish(result.id(),review);assertEquals(receipt,engine.publish(result.id(),review));assertEquals(7,marketing.offers().size());assertEquals(4,marketing.campaigns().size());assertEquals(d.baseline(),marketing.offer(d.baseline().id()));assertEquals(d.campaign(),marketing.campaign(d.campaign().id()));assertEquals(610,marketing.offer(receipt.offerId()).rules().underwriting().minimumScore());assertEquals(650,marketing.offer(receipt.offerId()).rules().bureau().minimumScore());assertThrows(Problem.class,()->marketing.saveOffer(receipt.offerId(),new OfferUpdate(1,d.offer())));var edited=engine.edit(d.id(),new EditDraft(2,d.name(),d.offer(),revised.rules()));assertEquals(3,edited.version());assertThrows(Problem.class,()->engine.publish(result.id(),new Review("Different publication note after edit",true)));}
    /** Verifies that stale catalog and untested draft cannot publish. */
    @Test void staleCatalogAndUntestedDraftCannotPublish()throws Exception{var d=draft();String p=population(200);var result=run(d,p);engine.edit(d.id(),new EditDraft(1,d.name(),d.offer(),d.rules()));assertEquals(409,assertThrows(Problem.class,()->engine.publish(result.id(),new Review("Reviewed old version statistics",true))).status);var fresh=draft();var newer=run(fresh,p);marketing.saveOffer(fresh.baseline().id(),new OfferUpdate(1,fresh.offer()));assertEquals(409,assertThrows(Problem.class,()->engine.publish(newer.id(),new Review("Reviewed but catalog is stale",true))).status);assertEquals(6,marketing.offers().size());}
    /** Verifies that mandatory gates and all three versioned stages execute in COBOL. */
    @Test void mandatoryGatesAndAllThreeVersionedStagesExecuteInCobol(){var p=new CobolBusinessPolicy(ROOT);var r=BusinessRules.defaults(Product.PERSONAL_LOAN);var customer=good();assertTrue(p.customer(customer,Product.PERSONAL_LOAN,r.underwriting(),"U",false).eligible());assertFalse(p.customer(customer,Product.PERSONAL_LOAN,change(r.underwriting(),"minimumScore",800),"U",false).eligible());assertFalse(p.customer(customer,Product.PERSONAL_LOAN,change(r.marketing(),"minimumTenureMonths",37),"M",false).eligible());assertTrue(p.customer(customer,Product.PERSONAL_LOAN,r.marketing(),"M",true).reasons().contains("GLOBAL_SUPPRESSION"));assertTrue(p.customer(EngineTest.change(customer,"marketingOptIn",false),Product.PERSONAL_LOAN,r.marketing(),"M",false).reasons().contains("CONSENT_REQUIRED"));assertTrue(p.customer(EngineTest.change(customer,"prescreenOptOut",null),Product.PERSONAL_LOAN,r.marketing(),"M",false).reasons().contains("PRESCREEN_OPT_OUT_OR_UNKNOWN"));var fractional=EngineTest.change(customer,"creditUtilizationPct",new BigDecimal("80.01"));assertFalse(p.customer(fractional,Product.CREDIT_CARD,BusinessRules.defaults(Product.CREDIT_CARD).underwriting(),"U",false).eligible());assertEquals("INCOMPLETE",p.customer(EngineTest.change(customer,"delinquencies12m",null),Product.PERSONAL_LOAN,change(r.marketing(),"maximumDelinquencies",0),"M",false).status());var facts=new Facts(FileStatus.MATCHED,780,new BigDecimal("500"),20,0,1,120,false,CLOCK.instant().toString());var profile=new BureauProfile("s","c",1,"SYNTHETIC",CLOCK.instant().toString(),facts);var input=new CreditInput("r","s","c",Product.PERSONAL_LOAN,new BigDecimal("10000"),new BigDecimal("7000"),"SELF_REPORTED",null,36,new BigDecimal("12"),r);try(var credit=new com.lending.engine.credit.CobolCreditPolicy(ROOT.resolve("build/licbbatch"),1,CLOCK)){assertEquals("APPROVED",credit.evaluate(input,profile).outcome());var stricter=new RuleSet(r.id(),2,r.createdAt(),r.underwriting(),r.marketing(),change(r.bureau(),"minimumScore",800));assertEquals("DECLINED",credit.evaluate(new CreditInput("r2","s","c",input.product(),input.amountUsd(),input.monthlyIncomeUsd(),input.incomeSource(),null,36,input.aprPct(),stricter),profile).outcome());}}
    /** Verifies that publication enters automatic customer flow without changing default offers. */
    @Test void publicationEntersAutomaticCustomerFlowWithoutChangingDefaultOffers()throws Exception{var d=draft();var r=d.rules();var relaxed=new RuleSet(r.id(),1,r.createdAt(),change(r.underwriting(),"minimumScore",610),r.marketing(),r.bureau());d=engine.edit(d.id(),new EditDraft(1,d.name(),d.offer(),relaxed));var result=run(d,population(200));var receipt=engine.publish(result.id(),new Review("Reviewed relaxed underwriting, bureau rules unchanged",true));var c=customers.create(EngineTest.change(good(),"creditScore",625));assertEquals(Status.INELIGIBLE,c.latest(Product.PERSONAL_LOAN).status());var marketingRun=marketing.automatic(c.id(),customers.pipeline(c.id()).token());var q=marketing.results(marketingRun.id(),0,100,null).items().stream().filter(a->a.offerId().equals(receipt.offerId())).findFirst().orElseThrow();assertEquals("QUALIFIED",q.outcome());assertTrue(marketing.results(marketingRun.id(),0,100,null).items().stream().filter(a->a.offerId().startsWith("DEMO-PL")).noneMatch(a->a.outcome().equals("QUALIFIED")));var source=new com.lending.engine.bureau.application.MarketingSource(active,CLOCK);source.published(new PublishedPolicies(new CobolBusinessPolicy(ROOT)));var ref=new Reference(marketingRun.id(),q.riskId(),q.id());assertEquals(d.rules(),source.current(ref).offer().rules());marketing.saveSuppression(c.id(),new SuppressionUpdate(0,new SuppressionInput(true,"TEST",null)));assertThrows(Problem.class,()->source.current(ref));var other=customers.create(EngineTest.change(good(),"creditScore",625));customers.importDecisions(List.of(new ImportDecision(other.id(),1,Product.PERSONAL_LOAN,Status.INELIGIBLE,List.of("BANK_DECLINED"),"BANK","decline", "BANK-1",CLOCK.instant().toString(),"2026-10-01")));var denied=marketing.automatic(other.id(),customers.pipeline(other.id()).token());assertTrue(marketing.results(denied.id(),0,100,null).items().stream().filter(a->a.offerId().equals(receipt.offerId())).noneMatch(a->a.outcome().equals("QUALIFIED")));}
    /** Verifies that real terminal edits forms and keeps mass generation out of customer mode. */
    @Test void realTerminalEditsFormsAndKeepsMassGenerationOutOfCustomerMode()throws Exception{try(var server=new ApiServer(customers,marketing,0,"test-local")){server.business(new com.lending.engine.simulation.api.SimulationApi(engine));server.start();var client=new ApiClient(server.port(),"test-local");assertThrows(RuntimeException.class,()->client.call("POST","simulations",new SimulationRequest(10,1L)));try(var terminal=new TerminalServer(0,client)){terminal.start();var process=new ProcessBuilder("s3270","-model","3279-2","127.0.0.1:"+terminal.port()).redirectError(ProcessBuilder.Redirect.DISCARD).start();try(var w=new PrintWriter(process.getOutputStream(),true);var in=new BufferedReader(new InputStreamReader(process.getInputStream()))){MarketingTest.cmd(w,in,"Wait(5,InputField)");choose(w,in,"2");assertTrue(screen(w,in).contains("Business Simulation Engine"));choose(w,in,"1");assertTrue(screen(w,in).contains("10000"));put(w,in,8,26,"60");MarketingTest.enter(w,in);assertEquals(1,engine.populations().size());assertEquals(0,customers.list(null,0,20).total());key(w,in,3);choose(w,in,"4");put(w,in,20,23,"1");MarketingTest.enter(w,in);assertTrue(screen(w,in).contains("Edit Step 1 underwriting"));choose(w,in,"2");put(w,in,6,31,"650");put(w,in,7,31,"2100.50");MarketingTest.enter(w,in);MarketingTest.enter(w,in);assertEquals(2,engine.store.list("DRAFT",Draft.class).get(0).version());assertEquals(new BigDecimal("2100.50"),engine.store.list("DRAFT",Draft.class).get(0).rules().underwriting().minimumIncomeUsd());assertTrue(screen(w,in).contains("v2"));Files.createDirectories(Path.of("target/presentation"));Files.writeString(Path.of("target/presentation/business-draft.txt"),screen(w,in));key(w,in,3);key(w,in,3);choose(w,in,"1");String menu=screen(w,in);assertFalse(menu.contains("Generate"));assertTrue(menu.contains("My marketing files"));}finally{process.destroyForcibly();}}}}
    /** Captures the current terminal screen for assertions. */
    private static String screen(PrintWriter w,BufferedReader r)throws Exception{return MarketingTest.cmd(w,r,"Ascii()");}
    /** Verifies that supplied approval cannot bypass stricter offer rules. */
    @Test void suppliedApprovalCannotBypassStricterOfferRules(){var customer=customers.create(good());customers.importDecisions(List.of(new ImportDecision(customer.id(),1,Product.PERSONAL_LOAN,Status.ELIGIBLE,List.of(),"BANK","approved","BANK-1",CLOCK.instant().toString(),"2026-10-01")));var r=BusinessRules.defaults(Product.PERSONAL_LOAN);var stricter=new RuleSet("STRICT",1,r.createdAt(),change(r.underwriting(),"minimumScore",800),r.marketing(),r.bureau());var offer=new Offer("STRICT",1,CLOCK.instant().toString(),marketing.offer("DEMO-PL-1").data(),stricter);var policy=new PublishedPolicies(new CobolBusinessPolicy(ROOT));assertFalse(policy.underwriting(customers.get(customer.id()),offer).eligible());assertEquals(Status.ELIGIBLE,customers.get(customer.id()).latest(Product.PERSONAL_LOAN).status());}
    /** Selects a terminal menu option in the test session. */
    private static void choose(PrintWriter w,BufferedReader r,String value)throws Exception{MarketingTest.cmd(w,r,"String(\""+value+"\")");MarketingTest.enter(w,r);}
    /** Sends a function key to the test terminal. */
    private static void key(PrintWriter w,BufferedReader r,int n)throws Exception{MarketingTest.cmd(w,r,"PF("+n+")");MarketingTest.cmd(w,r,"Wait(5,Unlock)");}
    /** Enters a test value into the selected field or JSON fixture. */
    private static void put(PrintWriter w,BufferedReader r,int row,int col,String value)throws Exception{MarketingTest.cmd(w,r,"MoveCursor("+row+","+col+")");MarketingTest.cmd(w,r,"EraseEOF()");MarketingTest.cmd(w,r,"String(\""+value+"\")");}
}
