/** Actual COBOL suppression boundaries, atomic customer admission and round-trip mainframe files. */
package com.lending.engine;
import com.lending.engine.execution.*;
import com.lending.engine.execution.Execution.*;
import com.lending.engine.execution.Execution.Package;
import com.lending.engine.domain.Model.*;
import com.lending.engine.infrastructure.*;
import com.lending.engine.application.CustomerEngine;
import com.lending.engine.marketing.domain.Marketing.*;
import com.lending.engine.offers.OfferSource.Terms;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.nio.charset.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;

/** Actual COBOL suppression boundaries, atomic customer admission and round-trip mainframe files. */
class ExecutionTest {
    @TempDir Path temp;static final Instant NOW=Instant.parse("2026-09-18T12:00:00Z");
    /** Builds a customer fixture with the required marketing consent. */
    static CustomerInput opted(){return EngineTest.change(EngineTest.good(),"marketingOptIn",true);}
    /** Builds the candidate offer or execution package used by the test. */
    static Package draft(String customer,String campaign,String source){var a=new Alternative("response-1",1,"risk-1","PL-BASE",1,"ORIGINAL",new Terms(new BigDecimal("10000"),new BigDecimal("10"),BigDecimal.ZERO,36),0.72,0.61,null,NOW.plusSeconds(864000).toString());var contact=new Contact(customer,1,"SYNTHETIC",customer+"@customers.invalid","+12025550101","SIMULATED DEMO CITY ZZ 00000 US",List.of("EMAIL"));return new Package(ExecutionStore.id(customer,campaign),0,customer,campaign,source,"EMAIL",contact,a.responseId(),a.kind(),null,List.of(a),"demo","ACTIVE",null,a.validUntil(),NOW.toString());}
    /** Verifies that imported assessment and simulation also queue automatically. */
    @Test void importedAssessmentAndSimulationAlsoQueueAutomatically()throws Exception{try(var store=new SqlStore("jdbc:h2:mem:"+UUID.randomUUID());var customers=new CustomerEngine(store,new CobolUnderwriter(Path.of("../build/liuwbatch"),temp),Clock.fixed(NOW,ZoneOffset.UTC))){var c=customers.create(opted());String old=customers.pipeline(c.id()).token();var decision=new ImportDecision(c.id(),1,Product.PERSONAL_LOAN,Status.INELIGIBLE,List.of("SOURCE_DECLINE"),"DEMO_BANK","decline","SOURCE-1",NOW.toString(),"2026-10-18");customers.importDecisions(List.of(decision));String next=customers.pipeline(c.id()).token();assertNotEquals(old,next);customers.importDecisions(List.of(decision));assertEquals(next,customers.pipeline(c.id()).token());var job=customers.simulate(new SimulationRequest(4,19L));ResponseIntegrationTest.await(()->customers.job(job.id()).status().equals("COMPLETED"));assertEquals(5,store.read(s->s.pendingPipelines(NOW.toEpochMilli(),20)).size());for(var row:customers.list(job.id(),0,20).items())assertNotNull(customers.contact(row.id()));customers.update(c.id(),new Update(1,EngineTest.change(opted(),"preferredChannels",List.of())));assertTrue(customers.contact(c.id()).preferredChannels().isEmpty());}}
    /** Verifies that actual COBOL enforces consent suppression preference and separate contact caps. */
    @Test void actualCobolEnforcesConsentSuppressionPreferenceAndSeparateContactCaps(){var p=new CobolExecutionPolicy(Path.of("..").toAbsolutePath());var fresh=new History(false,9999999999L,0);assertEquals("APPROVED",p.evaluate(opted(),null,true,true,fresh,NOW));assertEquals("MARKETING_CONSENT_REQUIRED",p.evaluate(EngineTest.good(),null,true,true,fresh,NOW));assertEquals("PRESCREEN_OPT_OUT_OR_UNKNOWN",p.evaluate(EngineTest.change(opted(),"prescreenOptOut",null),null,true,true,fresh,NOW));var suppression=new Suppression("c",1,NOW.toString(),new SuppressionInput(true,"TEST","2026-09-18"));assertEquals("GLOBAL_SUPPRESSION",p.evaluate(opted(),suppression,true,true,fresh,NOW));assertEquals("APPROVED",p.evaluate(opted(),suppression,true,true,fresh,NOW.plusSeconds(86400)));assertEquals("NO_ENABLED_CHANNEL",p.evaluate(opted(),null,true,false,fresh,NOW));assertEquals("OFFER_NOT_CURRENT",p.evaluate(opted(),null,false,true,fresh,NOW));assertEquals("EXECUTION_COOLDOWN",p.evaluate(opted(),null,true,true,new History(false,86399,1),NOW));assertEquals("APPROVED",p.evaluate(opted(),null,true,true,new History(false,86400,1),NOW));assertEquals("EXECUTION_WINDOW_LIMIT",p.evaluate(opted(),null,true,true,new History(false,86400,3),NOW));assertEquals("APPROVED",p.evaluate(opted(),null,true,true,new History(true,0,3),NOW));assertEquals("MARKETING_CONSENT_REQUIRED",p.evaluate(EngineTest.good(),null,true,true,new History(true,0,3),NOW));}
    /** Verifies that file bundle round trips copybook rejects partial files and withdraws. */
    @Test void fileBundleRoundTripsCopybookRejectsPartialFilesAndWithdraws()throws Exception{var files=new OutboundFiles(temp);var p=draft(UUID.randomUUID().toString(),"DEMO-PL","dispatch").state(1,"ACTIVE",null);files.write(p);var dir=files.directory(p.id());byte[] fixed=Files.readAllBytes(dir.resolve("offers.dat"));assertEquals(OutboundFiles.RECORD_LENGTH,fixed.length);String decoded=new String(fixed,Charset.forName("IBM037"));assertTrue(decoded.startsWith(p.id()));assertTrue(decoded.contains("10000.00"));assertTrue(decoded.contains("ORIGINAL"));var csv=files.download(p,"csv");assertTrue(new String(Base64.getDecoder().decode(csv.get("contentBase64").toString()),StandardCharsets.UTF_8).contains("synthetic_email"));assertThrows(java.io.IOException.class,()->files.download(p.state(2,"ACTIVE",null),"csv"));Files.writeString(dir.resolve("offers.csv"),"partial");assertThrows(java.io.IOException.class,()->files.download(p,"csv"));files.write(p);files.write(p.state(2,"WITHDRAWN","CONSENT_WITHDRAWN"));assertFalse(Files.exists(dir.resolve("offers.csv")));assertFalse(Files.exists(dir.resolve("offers.dat")));assertEquals("WITHDRAWN",Json.MAPPER.readTree(Files.readString(dir.resolve("manifest.json"))).path("status").asText());assertThrows(IllegalArgumentException.class,()->files.directory("../outside"));}
    /** Verifies that contact preferences and pipeline admission are atomic and survive restart. */
    @Test void contactPreferencesAndPipelineAdmissionAreAtomicAndSurviveRestart()throws Exception{String url="jdbc:h2:file:"+temp.resolve("customers");String id,first,second;try(var store=new SqlStore(url);var customers=new CustomerEngine(store,new CobolUnderwriter(Path.of("../build/liuwbatch"),temp.resolve("scratch")),Clock.fixed(NOW,ZoneOffset.UTC))){var c=customers.create(opted());id=c.id();first=customers.pipeline(id).token();assertEquals("QUEUED",customers.pipeline(id).state());assertEquals(List.of("EMAIL"),customers.contact(id).preferredChannels());assertTrue(customers.contact(id).email().endsWith(".invalid"));assertTrue(customers.contact(id).phone().matches("\\+120255501[0-9]{2}"));assertThrows(Problem.class,()->customers.create(EngineTest.change(opted(),"preferredChannels",List.of("FAX"))));assertThrows(IllegalStateException.class,()->store.write(s->{s.saveCustomer(new Customer(id,List.of(new Profile(id,2,"MANUAL_UPDATE",null,NOW.toString(),"SELF_REPORTED",EngineTest.change(opted(),"preferredChannels",List.of("SMS")))) ,c.decisions()));throw new IllegalStateException("rollback");}));assertEquals(first,customers.pipeline(id).token());assertEquals(List.of("EMAIL"),customers.contact(id).preferredChannels());customers.update(id,new Update(1,EngineTest.change(opted(),"preferredChannels",List.of("SMS","EMAIL"))));second=customers.pipeline(id).token();assertNotEquals(first,second);store.write(s->{s.savePipeline(new Pipeline(id,first,"COMPLETED","stale",NOW.toString(),"stale"),0);return null;});assertEquals(second,customers.pipeline(id).token());assertEquals("QUEUED",customers.pipeline(id).state());assertEquals(List.of("SMS","EMAIL"),customers.contact(id).preferredChannels());}
        try(var store=new SqlStore(url)){assertEquals(second,store.read(s->s.pipeline(id)).token());assertEquals(1,store.read(s->s.pendingPipelines(NOW.toEpochMilli(),20)).size());}

        try(var c=java.sql.DriverManager.getConnection(url,"sa","");var s=c.createStatement()){s.execute("DELETE FROM customer_contacts");s.execute("DELETE FROM customer_pipeline");}
        try(var store=new SqlStore(url)){assertNotNull(store.read(s->s.contact(id)));assertEquals(List.of("SMS","EMAIL"),store.read(s->s.contact(id)).preferredChannels());assertNull(store.read(s->s.pipeline(id)));}
    }
}
