/**
 * Business-published rule and service-boundary regression covers personalization, storage copies,
 * withdrawal and callback capacity.
 */
package com.lending.engine;
import com.lending.engine.offers.*;
import com.lending.engine.offers.OfferSource.*;
import com.lending.engine.api.ApiServer;
import com.lending.engine.bureau.domain.Bureau.*;
import com.lending.engine.bureau.infrastructure.KafkaTransport;
import com.lending.engine.domain.Model.*;
import com.lending.engine.infrastructure.Json;
import com.lending.engine.response.api.ResponseApi;
import com.lending.engine.terminal.*;
import com.lending.engine.storage.*;
import static com.lending.engine.bureau.infrastructure.BureauDatabase.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.math.BigDecimal;
import java.net.*;
import java.net.http.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.TimeUnit;

/**
 * Business-published rule and service-boundary regression covers personalization, storage copies,
 * withdrawal and callback capacity.
 */
@EnabledIfEnvironmentVariable(named="BUREAU_TEST_DATABASE_URL",matches=".+")
class OfferCreationIntegrationTest {
    @TempDir Path temp;ResponseIntegrationTest f;OfferSource source;ApiServer api;Process service;KafkaTransport kafka;
    StorageViews copies;
    String serviceSchema="marketing_e2e_"+UUID.randomUUID().toString().replace("-","");String sourceToken="s".repeat(40),operatorToken="o".repeat(40),serviceToken="m".repeat(40);int servicePort;
    /** Creates isolated test resources and wires the workflow under test. */
    @BeforeEach void setup()throws Exception{f=new ResponseIntegrationTest();f.temp=temp;f.clock.now=java.time.Instant.now();f.setup();source=new OfferSource(f.customers,f.bureau,f.responses,Path.of("..").toAbsolutePath(),f.clock);try(var socket=new ServerSocket(0)){servicePort=socket.getLocalPort();}api=new ApiServer(f.customers,f.marketing,0,operatorToken);api.responses(new ResponseApi(f.responses));api.offers(new OfferApi(source,sourceToken,serviceToken,servicePort));api.start();}
    /** Closes test resources and removes only the temporary artifacts owned by the test. */
    @AfterEach void cleanup()throws Exception{if(copies!=null)copies.close();if(service!=null){service.destroy();if(!service.waitFor(15,TimeUnit.SECONDS))service.destroyForcibly().waitFor(5,TimeUnit.SECONDS);}if(kafka!=null){kafka.close();try(var admin=org.apache.kafka.clients.admin.Admin.create(Map.of("bootstrap.servers","127.0.0.1:9092"))){admin.deleteTopics(List.of(f.queue.inputTopic,f.queue.resultsTopic,f.queue.dlqTopic,f.repository.qualificationTopic,f.repository.decisionTopic,serviceSchema+".storage")).all().get(20,TimeUnit.SECONDS);}}if(api!=null)api.close();if(f!=null&&f.db!=null)f.db.tx(c->{execute(c,"DROP SCHEMA IF EXISTS "+serviceSchema+" CASCADE");execute(c,"DROP SCHEMA IF EXISTS "+serviceSchema+"_c CASCADE");execute(c,"DROP SCHEMA IF EXISTS "+serviceSchema+"_w CASCADE");return null;});if(f!=null)f.cleanup();}
    /** Builds current independent bureau facts suitable for offer requalification. */
    private Facts freshFacts(){return CreditPolicyTest.change(CreditPolicyTest.facts(),"reportedAt",f.clock.instant().toString(),Facts.class);}
    /** Verifies that published rules reach credit HTTP and personalized term requalification. */
    @Test void publishedRulesReachCreditHttpAndPersonalizedTermRequalification(){
        var rules=com.lending.engine.simulation.domain.BusinessRules.defaults(Product.PERSONAL_LOAN);
        var scoped=new com.lending.engine.simulation.domain.BusinessRules.RuleSet("BR-INTEGRATION",1,f.clock.instant().toString(),BusinessSimulationTest.change(rules.underwriting(),"minimumScore",610),rules.marketing(),BusinessSimulationTest.change(rules.bureau(),"minimumScore",800));
        var policies=new com.lending.engine.simulation.application.PublishedPolicies(new com.lending.engine.simulation.infrastructure.CobolBusinessPolicy(Path.of("..").toAbsolutePath()));f.marketing.published(policies);f.source.published(policies);
        var old=f.marketing.offer("DEMO-PL-1");var campaign=f.marketing.campaign("DEMO-PL").data();
        f.store.write(s->{s.saveOffer(new com.lending.engine.marketing.domain.Marketing.Offer("BUS-TEST-PL",1,f.clock.instant().toString(),old.data(),scoped));s.saveCampaign(new com.lending.engine.marketing.domain.Marketing.Campaign("BUS-TEST-PL",1,f.clock.instant().toString(),new com.lending.engine.marketing.domain.Marketing.CampaignInput("Published test",true,campaign.startsOn(),campaign.endsOn(),1,1000,0,false,List.of("BUS-TEST-PL"))));return null;});
        var input=EngineTest.change(EngineTest.change(EngineTest.change(EngineTest.good(),"creditScore",625),"marketingOptIn",true),"externalReference",null);var customer=f.customers.create(input);assertEquals(Status.INELIGIBLE,customer.latest(Product.PERSONAL_LOAN).status());
        var run=f.marketing.automatic(customer.id(),f.customers.pipeline(customer.id()).token());var q=f.marketing.results(run.id(),0,100,null).items().stream().filter(x->x.offerId().equals("BUS-TEST-PL")).findFirst().orElseThrow();assertEquals("QUALIFIED",q.outcome());var ref=new Reference(run.id(),q.riskId(),q.id());
        f.facts(ref,CreditPolicyTest.change(freshFacts(),"creditScore",810,Facts.class));f.bureau.submit(new Submit("published-credit",ref));f.bureau.processOne();f.responses.projectPending();var response=f.responses.get(com.lending.engine.response.infrastructure.ResponseRepository.id(ref));assertTrue(response.marketingEligible());assertEquals(scoped,response.qualifiedOffer().rules());assertEquals("BR-INTEGRATION-v1",response.bureauDecision().policyVersion());
        var ctx=source.context(response.id());var t=ctx.original();var proposal=new Proposal("business-variant",response.id(),response.version(),ctx.policyVersion(),new Terms(t.amountUsd(),t.aprPct().subtract(BigDecimal.ONE),t.annualFeeUsd(),t.termMonths()));var approved=source.qualify(proposal);assertTrue(approved.approved(),approved.toString());assertEquals("BR-INTEGRATION-v1",approved.underwritingPolicyVersion());
        f.facts(ref,CreditPolicyTest.change(freshFacts(),"creditScore",799,Facts.class));var denied=source.qualify(new Proposal("business-declined-variant",response.id(),response.version(),ctx.policyVersion(),proposal.terms()));assertFalse(denied.approved());assertTrue(denied.checks().contains("BUREAU_DECLINED"));
    }
    /** Verifies that concurrent terminal proxies leave capacity for qualification callbacks. */
    @Test @Timeout(20) void concurrentTerminalProxiesLeaveCapacityForQualificationCallbacks()throws Exception{
        var entered=new java.util.concurrent.CountDownLatch(4);var release=new java.util.concurrent.CountDownLatch(1);var workers=java.util.concurrent.Executors.newFixedThreadPool(4);
        var downstream=com.sun.net.httpserver.HttpServer.create(new InetSocketAddress("127.0.0.1",servicePort),8);downstream.setExecutor(workers);downstream.createContext("/",x->{entered.countDown();try{release.await(10,TimeUnit.SECONDS);byte[] bytes="{}".getBytes();x.sendResponseHeaders(200,bytes.length);x.getResponseBody().write(bytes);}catch(InterruptedException e){Thread.currentThread().interrupt();}finally{x.close();}});downstream.start();
        try{var http=HttpClient.newHttpClient();var calls=new ArrayList<java.util.concurrent.CompletableFuture<HttpResponse<String>>>();var request=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+api.port()+"/api/v1/offer-creation/health")).header("Authorization","Bearer "+operatorToken).timeout(java.time.Duration.ofSeconds(15)).GET().build();for(int i=0;i<4;i++)calls.add(http.sendAsync(request,HttpResponse.BodyHandlers.ofString()));assertTrue(entered.await(5,TimeUnit.SECONDS));
            assertEquals(503,http.send(request,HttpResponse.BodyHandlers.ofString()).statusCode());var callback=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+api.port()+"/api/v1/offer-source/policy")).header("Authorization","Bearer "+sourceToken).timeout(java.time.Duration.ofSeconds(3)).GET().build();assertEquals(200,http.send(callback,HttpResponse.BodyHandlers.ofString()).statusCode());release.countDown();for(var call:calls)assertEquals(200,call.get(5,TimeUnit.SECONDS).statusCode());
        }finally{release.countDown();downstream.stop(0);workers.shutdownNow();}
    }
    /** Completes an approved bureau assessment for the test qualification. */
    private com.lending.engine.response.domain.DecisionResponse.Response approve(Reference ref,String id){f.facts(ref,freshFacts());f.bureau.submit(new Submit(id,ref));f.bureau.processOne();f.responses.projectPending();return f.responses.get(com.lending.engine.response.infrastructure.ResponseRepository.id(ref));}
    /** Verifies that finalized prescreen source requires no bureau and tracks withdrawal. */
    @Test void finalizedPrescreenSourceRequiresNoBureauAndTracksWithdrawal(){var ref=f.finalized();var client=new ApiClient(api.port(),sourceToken);var page=client.call("GET","offer-source/prescreen?limit=100",null);assertFalse(page.path("items").isEmpty());for(var row:page.path("items")){assertEquals("AWAITING_BUREAU",row.path("status").asText());assertTrue(row.path("terms").path("amountUsd").asDouble()>0);}assertEquals("0",f.db.tx(c->scalar(c,"SELECT count(*) FROM bureau_work")));f.marketing.cancel(ref.runId());for(var row:client.call("GET","offer-source/prescreen?limit=100",null).path("items"))assertEquals("WITHDRAWN",row.path("status").asText());}
    /** Verifies that actual COBOL envelope and fresh bureau decision qualify exact variant. */
    @Test void actualCobolEnvelopeAndFreshBureauDecisionQualifyExactVariant(){var ref=f.finalized();var r=approve(ref,"base");var ctx=source.context(r.id());var base=ctx.original();var terms=new Terms(base.amountUsd(),base.aprPct().subtract(BigDecimal.ONE),base.annualFeeUsd(),base.termMonths());var request=new Proposal("variant",r.id(),r.version(),ctx.policyVersion(),terms);var approval=source.qualify(request);assertTrue(approval.approved(),approval.toString());assertNotNull(approval.bureauDecisionId());assertEquals("SIM-2026-001",approval.underwritingPolicyVersion());assertEquals(approval,source.qualify(request));assertEquals(approval,source.check(approval.id()));assertEquals(1,f.customers.get(r.customerId()).current().version());
        var invalid=source.qualify(new Proposal("outside",r.id(),r.version(),ctx.policyVersion(),new Terms(base.amountUsd(),base.aprPct().add(BigDecimal.ONE),base.annualFeeUsd(),base.termMonths())));assertFalse(invalid.approved());assertTrue(invalid.checks().contains("APR_OUTSIDE_ENVELOPE"));
        f.facts(ref,CreditPolicyTest.change(freshFacts(),"creditScore",600,Facts.class));var declined=source.qualify(new Proposal("fresh-bureau",r.id(),r.version(),ctx.policyVersion(),terms));assertFalse(declined.approved());assertTrue(declined.checks().contains("BUREAU_DECLINED"));f.marketing.cancel(ref.runId());assertThrows(Problem.class,()->source.check(approval.id()));}
    /** Verifies that service credential is scoped and training features exclude names and credit scores. */
    @Test void serviceCredentialIsScopedAndTrainingFeaturesExcludeNamesAndCreditScores()throws Exception{var job=f.customers.simulate(new SimulationRequest(100,42L));ResponseIntegrationTest.await(()->f.customers.job(job.id()).status().equals("COMPLETED"));var client=new ApiClient(api.port(),sourceToken);var features=client.call("GET","offer-source/features?batchId="+job.id()+"&limit=200",null);assertEquals(100,features.path("items").size());for(String field:List.of("displayName","externalReference","creditScore","customerText"))assertFalse(features.toString().contains("\""+field+"\""));var unauthorized=HttpClient.newHttpClient().send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+api.port()+"/api/v1/customers")).header("Authorization","Bearer "+sourceToken).GET().build(),HttpResponse.BodyHandlers.ofString());assertEquals(401,unauthorized.statusCode());}
    /** Verifies that separate marketing process trains creates publishes choices and withdraws. */
    @Test @Timeout(180) void separateMarketingProcessTrainsCreatesPublishesChoicesAndWithdraws()throws Exception{
        var storageClient=new StorageClient(servicePort,serviceToken);String topic=serviceSchema+".storage";
        copies=new StorageViews(new OfferCopyLoader(new OfferCopyStore(System.getenv("BUREAU_TEST_DATABASE_URL"),serviceSchema+"_c"),storageClient,"127.0.0.1:9092",topic),new OfferCopyLoader(new OfferCopyStore(System.getenv("BUREAU_TEST_DATABASE_URL"),serviceSchema+"_w"),storageClient,"127.0.0.1:9092",topic),source);api.storage(copies);copies.start();
        var ref=f.finalized();var r=approve(ref,"original");var job=f.customers.simulate(new SimulationRequest(1000,7251L));ResponseIntegrationTest.await(()->f.customers.job(job.id()).status().equals("COMPLETED"));
        Files.createDirectories(temp.resolve("runtime"));Files.writeString(temp.resolve("runtime/marketing-source-token"),sourceToken);Files.writeString(temp.resolve("runtime/marketing-api-token"),serviceToken);
        kafka=new KafkaTransport(f.bureau,"127.0.0.1:9092",List.of(f.repository.qualificationTopic,f.repository.decisionTopic));kafka.start();
        var builder=new ProcessBuilder("java","-Dengine.home="+temp,"-Dengine.api.port="+api.port(),"-Dmarketing.api.port="+servicePort,"-Dmarketing.db.schema="+serviceSchema,"-Dmarketing.auto.train=false","-Dmarketing.kafka.group="+serviceSchema,"-Dstorage.kafka.topic="+serviceSchema+".storage","-Dmarketing.kafka.topic="+f.repository.qualificationTopic,"-Dorg.slf4j.simpleLogger.defaultLogLevel=warn","-jar",Path.of("../marketing-service/target/marketing-offers-1.0.0.jar").toAbsolutePath().toString());builder.environment().put("DATABASE_URL",System.getenv("BUREAU_TEST_DATABASE_URL"));builder.redirectErrorStream(true).redirectOutput(temp.resolve("marketing-test.log").toFile());service=builder.start();var client=new ApiClient(api.port(),operatorToken);
        ResponseIntegrationTest.await(()->{try{return client.call("GET","offer-creation/health",null).has("inbox");}catch(Exception e){return false;}});
        ResponseIntegrationTest.await(()->{try{return !client.call("GET","offer-creation/customers/"+r.customerId()+"/offers",null).path("items").isEmpty();}catch(Exception e){return false;}});
        var before=client.call("GET","offer-creation/offers/"+r.id(),null);assertTrue(before.path("personalized").isNull());assertEquals("WAITING_FOR_MODEL",before.path("personalizationStatus").asText());
        client.call("POST","offer-creation/training",Map.of("batchId",job.id(),"seed",17));ResponseIntegrationTest.await(()->{try{return !client.call("GET","offer-creation/offers/"+r.id(),null).path("personalized").isNull();}catch(Exception e){return false;}});
        var offer=client.call("GET","offer-creation/offers/"+r.id(),null);assertTrue(offer.path("deltas").path("fitScore").asDouble()>0);assertNotEquals(offer.path("original").path("terms"),offer.path("personalized").path("terms"));assertTrue(client.call("GET","offer-creation/models",null).get(0).path("metrics").path("testCount").asInt()>0);Files.writeString(Path.of("target/marketing-offer-example.json"),offer.toPrettyString());
        try(var terminal=new TerminalServer(0,client)){terminal.start();var process=new ProcessBuilder("s3270","-model","3279-2","127.0.0.1:"+terminal.port()).redirectError(ProcessBuilder.Redirect.DISCARD).start();try(var writer=new PrintWriter(process.getOutputStream(),true);var reader=new BufferedReader(new InputStreamReader(process.getInputStream()))){MarketingTest.cmd(writer,reader,"Wait(5,InputField)");for(String choice:List.of("2","7","9","7","2",r.customerId(),"1")){MarketingTest.cmd(writer,reader,"String(\""+choice+"\")");MarketingTest.enter(writer,reader);}String screen=MarketingTest.cmd(writer,reader,"Ascii()");assertTrue(screen.contains("PERSONALIZED"),screen);assertTrue(screen.contains("Monthly payment"),screen);MarketingTest.cmd(writer,reader,"String(\"P\")");MarketingTest.enter(writer,reader);assertTrue(MarketingTest.cmd(writer,reader,"Ascii()").contains("Selected PERSONALIZED"));MarketingTest.cmd(writer,reader,"String(\"O\")");MarketingTest.enter(writer,reader);assertTrue(MarketingTest.cmd(writer,reader,"Ascii()").contains("Selected ORIGINAL"));MarketingTest.cmd(writer,reader,"Quit()");}finally{process.destroyForcibly();}}
        ResponseIntegrationTest.await(()->{try{return client.call("GET","customers/"+r.customerId()+"/offers/"+r.id(),null).path("selection").path("kind").asText().equals("ORIGINAL");}catch(Exception e){return false;}});
        var stored=client.call("GET","offer-creation/storage/offers/"+r.id(),null);StorageContract.validate(stored);Files.writeString(Path.of("target/offer-storage-example.json"),stored.toPrettyString());
        ResponseIntegrationTest.await(()->client.call("GET","warehouse/offers/"+r.id(),null).path("offer").path("version").asLong()>=stored.path("offer").path("version").asLong());
        assertEquals(1,client.call("GET","customers/"+r.customerId(),null).path("offerView").path("items").size());
        try(var terminal=new TerminalServer(0,client)){terminal.start();var process=new ProcessBuilder("s3270","-model","3279-2","127.0.0.1:"+terminal.port()).redirectError(ProcessBuilder.Redirect.DISCARD).start();try(var writer=new PrintWriter(process.getOutputStream(),true);var reader=new BufferedReader(new InputStreamReader(process.getInputStream()))){MarketingTest.cmd(writer,reader,"Wait(5,InputField)");MarketingTest.cmd(writer,reader,"String(\"2\")");MarketingTest.enter(writer,reader);MarketingTest.cmd(writer,reader,"String(\"7\")");MarketingTest.enter(writer,reader);MarketingTest.cmd(writer,reader,"String(\"2\")");MarketingTest.enter(writer,reader);MarketingTest.cmd(writer,reader,"MoveCursor(18,18)");MarketingTest.cmd(writer,reader,"String(\""+r.customerId()+"\")");MarketingTest.enter(writer,reader);assertTrue(MarketingTest.cmd(writer,reader,"Ascii()").contains("F6=Offers"));MarketingTest.cmd(writer,reader,"PF(6)");MarketingTest.cmd(writer,reader,"Wait(5,InputField)");MarketingTest.cmd(writer,reader,"String(\"1\")");MarketingTest.enter(writer,reader);String screen=MarketingTest.cmd(writer,reader,"Ascii()");assertTrue(screen.contains("PRE-SCREEN"),screen);assertTrue(screen.contains("Selected: ORIGINAL"),screen);MarketingTest.cmd(writer,reader,"String(\"P\")");MarketingTest.enter(writer,reader);assertTrue(MarketingTest.cmd(writer,reader,"Ascii()").contains("Selected PERSONALIZED"));MarketingTest.cmd(writer,reader,"Quit()");}finally{process.destroyForcibly();}}
        f.marketing.cancel(ref.runId());assertTrue(client.call("GET","customers/"+r.customerId()+"/offers",null).path("items").isEmpty());f.responses.get(r.id());ResponseIntegrationTest.await(()->client.call("GET","offer-creation/customers/"+r.customerId()+"/offers",null).path("items").isEmpty());assertThrows(IllegalArgumentException.class,()->client.call("POST","offer-creation/offers/"+r.id()+"/selections",Map.of("requestId","stale","sourceVersion",r.version(),"kind","ORIGINAL")));
        ResponseIntegrationTest.await(()->!client.call("GET","warehouse/offers/"+r.id(),null).path("offer").path("preScreen").path("visible").asBoolean());assertTrue(client.call("GET","warehouse/offers/"+r.id()+"/history",null).size()>=4);
        ResponseIntegrationTest.await(()->copies.customer.health().get("kafka").equals("RUNNING")&&copies.warehouse.health().get("kafka").equals("RUNNING"));
        ResponseIntegrationTest.await(()->client.call("GET","offer-creation/storage/health",null).path("pendingPublication").asLong()==0);
        try(var admin=org.apache.kafka.clients.admin.Admin.create(Map.of("bootstrap.servers","127.0.0.1:9092"))){for(String group:List.of(copies.customer.store.schema,copies.warehouse.store.schema)){var offsets=admin.listConsumerGroupOffsets(group+"-storage-v1").partitionsToOffsetAndMetadata().get(10,TimeUnit.SECONDS);assertTrue(offsets.values().stream().anyMatch(offset->offset.offset()>0),"Kafka copy consumer did not acknowledge a storage record");}}
        ResponseIntegrationTest.await(()->client.call("GET","offer-creation/health",null).path("kafka").asText().equals("RUNNING"));assertTrue(client.call("GET","offer-creation/offers/"+r.id()+"/history",null).size()>=3);ResponseIntegrationTest.await(()->Long.parseLong(f.db.tx(c->scalar(c,"SELECT count(*) FROM "+serviceSchema+".inbox WHERE event_id NOT LIKE 'snapshot:%'")))>0);
    }
}
