/**
 * HTTP-only Business workbench: form revisions, synthetic populations, paged evidence and explicit
 * reviewed publication.
 */
package com.lending.engine.terminal;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.lending.engine.infrastructure.Json;
import java.math.BigDecimal;
import java.util.*;

/**
 * HTTP-only Business workbench: form revisions, synthetic populations, paged evidence and explicit
 * reviewed publication.
 */
final class SimulationTerminal {
    private static final int BLUE=0xf1,CYAN=0xf5,YELLOW=0xf6,WHITE=0xf7;
    private final ApiClient api;private String view="HOME",draftId,runId,populationId,kind,section,notice="";private int offset,page;private JsonNode rows,draft,run,catalog,receipt;private ObjectNode form;private List<String> keys=List.of();private List<String> reportLines=List.of();
    private String reportParent="RUN";private int parentOffset;
    /** Initializes simulation terminal with the supplied configuration and dependencies. */
    SimulationTerminal(ApiClient api){this.api=api;}
    /** Clears the screen state before beginning a new terminal interaction. */
    void reset(){view="HOME";offset=0;page=0;notice="";}
    /** Opens the isolated population-generation form in Business mode. */
    void generate(){reset();view="GENERATE";}
    /** Loads simulation data through the public HTTP API. */
    private JsonNode get(String path){return api.call("GET","business/"+path,null);}
    /** Submits a Business simulation command through the public HTTP API. */
    private JsonNode post(String path,Object data){return api.call("POST","business/"+path,data);}
    /**
     * Processes terminal keys and submitted fields for the active screen, issuing commands through HTTP
     * APIs.
     */
    String handle(int aid,Map<String,String> v){if(aid==0xf3){if(view.equals("HOME"))return "MODE";if(view.equals("REPORT")||view.equals("ROW")){view=reportParent;offset=parentOffset;return null;}if(Set.of("EDIT","DRAFT","NEW","DRAFTS").contains(view))view=view.equals("EDIT")?"DRAFT":"HOME";else if(Set.of("ROWS","PUBLISH").contains(view))view="RUN";else view="HOME";offset=0;page=0;return null;}
        if(aid==0xf7||aid==0xf8){int step=aid==0xf8?1:-1;if(view.equals("EDIT")){capture(v);page=Math.max(0,Math.min((keys.size()-1)/8,page+step));}else if(view.equals("REPORT")||view.equals("ROW"))offset=Math.max(0,Math.min(Math.max(0,reportLines.size()-1),offset+step*13));else offset=Math.max(0,offset+step*8);return null;}
        if(aid!=0x7d)return null;String choice=v.getOrDefault("choice","").trim();if(choice.matches("0[0-9]"))choice=choice.substring(1);notice="";
        switch(view){
            case "HOME"->{offset=0;switch(choice){case "1"->view="GENERATE";case "2"->view="POPULATIONS";case "3"->view="DRAFTS";case "4"->{catalog=get("catalog");view="NEW";}case "5"->view="RUNS";case "6"->view="PUBLICATIONS";case "7"->{return "MENU";}default->throw new IllegalArgumentException("Choose 01-07");}}
            case "GENERATE"->{var p=post("populations",Map.of("count",Integer.parseInt(v.get("count").trim()),"seed",Long.parseLong(v.get("seed").trim())));populationId=p.path("id").asText();view="POPULATIONS";notice="Created "+p.path("count").asText()+" isolated customers. Active customer data unchanged.";}
            case "POPULATIONS"->{populationId=pick(choice).path("id").asText();offset=0;view="PEOPLE";}
            case "PEOPLE"->{var person=pick(choice);lines(person);view="ROW";section="Synthetic input / independent bureau facts";}
            case "NEW"->{var baseline=pick(choice);String campaign=null;for(var c:catalog.path("campaigns"))for(var id:c.path("data").path("offerIds"))if(id.asText().equals(baseline.path("id").asText())&&campaign==null)campaign=c.path("id").asText();if(campaign==null)throw new IllegalArgumentException("Baseline needs a campaign");draft=post("drafts",Map.of("name",v.get("name").trim(),"baselineOfferId",baseline.path("id").asText(),"campaignId",campaign));draftId=draft.path("id").asText();view="DRAFT";offset=0;}
            case "DRAFTS"->{draftId=pick(choice).path("id").asText();draft=get("drafts/"+draftId);view="DRAFT";offset=0;}
            case "DRAFT"->{draft=get("drafts/"+draftId);switch(choice){case "1"->edit("offer");case "2"->edit("underwriting");case "3"->edit("marketing");case "4"->edit("bureau");case "5"->{view="RUNFORM";offset=0;}case "6"->{lines(draft);section="Current immutable draft / catalog snapshots";view="REPORT";}default->throw new IllegalArgumentException("Choose 1-6");}}
            case "EDIT"->{capture(v);if(page<(keys.size()-1)/8){page++;break;}var body=(ObjectNode)Json.MAPPER.createObjectNode();body.put("expectedVersion",draft.path("version").asInt());body.put("name",draft.path("name").asText());body.set("offer",kind.equals("offer")?form:draft.path("offer"));var rules=(ObjectNode)draft.path("rules").deepCopy();if(!kind.equals("offer"))rules.set(kind,form);body.set("rules",rules);draft=api.call("PUT","business/drafts/"+draftId,body);view="DRAFT";notice="Saved immutable draft and rules v"+draft.path("version").asText()+". Run this version before publishing.";}
            case "RUNFORM"->{var selected=pick(choice);populationId=selected.path("id").asText();run=post("runs",Map.of("draftId",draftId,"draftVersion",draft.path("version").asInt(),"populationId",populationId,"seed",Long.parseLong(v.get("seed").trim())));runId=run.path("id").asText();view="RUN";offset=0;}
            case "RUNS"->{runId=pick(choice).path("id").asText();run=get("runs/"+runId);view="RUN";offset=0;}
            case "RUN"->{run=get("runs/"+runId);if(choice.isBlank())break;if(!run.path("status").asText().equals("COMPLETED"))throw new IllegalArgumentException("Wait for the comparison to complete; ENTER refreshes");switch(choice){case "1"->{section="Overall comparison";lines(run.path("report").path("overall"));view="REPORT";}case "2"->{section="Held-out test comparison";lines(run.path("report").path("heldOutTest"));view="REPORT";}case "3"->{section="Cohort impact comparisons";lines(run.path("report").path("cohorts"));view="REPORT";}case "4"->{section="Model, denominators and limitations";var info=Json.MAPPER.createObjectNode();info.set("model",run.path("report").path("model"));info.set("assumptions",run.path("report").path("assumptions"));info.set("costHorizon",run.path("report").path("costHorizon"));lines(info);view="REPORT";}case "5"->{view="ROWS";offset=0;}case "6"->view="PUBLISH";default->throw new IllegalArgumentException("Choose 1-6");}}
            case "ROWS"->{lines(pick(choice));section="Customer eligibility, reasons and paired metrics";view="ROW";}
            case "PUBLISH"->{if(!v.get("confirm").trim().equalsIgnoreCase("P"))throw new IllegalArgumentException("Type P to publish after reviewing the results");receipt=post("runs/"+runId+"/publish",Map.of("confirm",true,"note",v.get("note").trim()));view="RECEIPT";}
            case "PUBLICATIONS"->{receipt=pick(choice);view="RECEIPT";}
            case "RECEIPT"->view="HOME";
            default->{}
        }return null;
    }
    /** Opens a versioned simulation rule or offer form for editing. */
    private void edit(String selected){kind=selected;form=(ObjectNode)(kind.equals("offer")?draft.path("offer"):draft.path("rules").path(kind)).deepCopy();keys=kind.equals("offer")?List.of("name","active","startsOn","endsOn","minimumAmountUsd","maximumAmountUsd","illustrativeAprPct","annualFeeUsd","termMonths"):kind.equals("bureau")?List.of("minimumScore","minimumIncomeUsd","maximumDtiPct","maximumUtilizationPct","maximumDelinquencies","maximumAmountUsd","maximumLtvPct","maximumInquiries","minimumHistoryMonths","maximumReportAgeDays","allowBankruptcy"):List.of("minimumScore","minimumIncomeUsd","maximumDtiPct","maximumUtilizationPct","maximumDelinquencies","maximumAmountUsd","incomeMultiple","maximumLtvPct","maximumVehicleAge","minimumTenureMonths","excludeExistingProduct");page=0;view="EDIT";}
    /** Copies submitted terminal fields into the current form or test snapshot. */
    private void capture(Map<String,String> v){for(int i=page*8;i<Math.min(keys.size(),page*8+8);i++){String key=keys.get(i),value=v.get(key).trim();var previous=form.path(key);if(previous.isBoolean()){if(!Set.of("Y","N").contains(value.toUpperCase(Locale.ROOT)))throw new IllegalArgumentException(label(key)+": use Y or N");form.put(key,value.equalsIgnoreCase("Y"));}else if(key.endsWith("Usd")||key.equals("illustrativeAprPct"))form.put(key,new BigDecimal(value));else if(previous.isIntegralNumber())form.put(key,Integer.parseInt(value));else if(previous.isNumber())form.put(key,new BigDecimal(value));else form.put(key,value);}}
    /** Returns the selected displayed row after validating the entered row number. */
    private JsonNode pick(String value){int index=Integer.parseInt(value)-1;if(rows==null||index<0||index>=rows.size())throw new IllegalArgumentException("Choose a displayed row");return rows.get(index);}
    /** Builds the paged text rows used to display simulation evidence. */
    private void lines(JsonNode value){reportParent=view;parentOffset=offset;var text=new ArrayList<String>();flatten("",value,text);reportLines=List.copyOf(text);offset=0;}
    /** Flattens nested simulation results into displayable rows. */
    private static void flatten(String path,JsonNode n,List<String> lines){if(n.isObject()){n.fields().forEachRemaining(e->flatten(path.isEmpty()?e.getKey():path+" / "+e.getKey(),e.getValue(),lines));}else if(n.isArray()){int i=0;for(var v:n)flatten(path+" ["+(i++)+"]",v,lines);}else{String value=n.isNull()?"n/a":n.isFloatingPointNumber()?String.format(Locale.ROOT,"%.3f",n.asDouble()):n.asText();String line=path+": "+value;for(int i=0;i<line.length();i+=75)lines.add((i==0?"":"  ")+line.substring(i,Math.min(line.length(),i+75)));}}
    /** Renders the current workflow state and input fields on the terminal screen. */
    String draw(TerminalServer.Screen s){s.center(3,"Business Simulation Engine",WHITE);String footer="ENTER=Continue F3=Back";
        switch(view){
            case "HOME"->{String[] options={"Generate synthetic customers (up to 10,000)","Inspect isolated populations","Open offer / rule drafts","Create a draft from an existing catalog offer","Review simulation results / impact analysis","Publication history","Active customer / campaign operations"};for(int i=0;i<options.length;i++)s.text(6+i,12,String.format("%02d. %s",i+1,options[i]),BLUE);s.text(16,3,"Drafts and synthetic populations are isolated from Customer processing.",WHITE);s.text(18,3,"Publication requires your review; consent and suppression stay mandatory.",CYAN);s.menuField();footer="ENTER=Continue F3=Change mode";}
            case "GENERATE"->{s.text(5,2,"Reproducible mixed eligible, ineligible and incomplete customers.",WHITE);s.field("count",8,26,5,"10000","Customer count 60-10000");s.field("seed",10,26,19,"20260918","Population seed");s.text(14,2,"Independent synthetic bureau facts and suppression examples included.",BLUE);s.text(16,2,"No active customers, reservations, messages or marketing files created.",CYAN);s.text(18,2,"Generate, draft offer/rules, compare, then decide whether to publish.",WHITE);}
            case "POPULATIONS","DRAFTS","RUNS","PUBLICATIONS","NEW","RUNFORM"->{String resource=switch(view){case "POPULATIONS","RUNFORM"->"populations";case "DRAFTS"->"drafts";case "RUNS"->"runs";case "PUBLICATIONS"->"publications";default->"";};JsonNode all=view.equals("NEW")?catalog.path("offers"):get(resource);var list=Json.MAPPER.createArrayNode();offset=Math.min(offset,Math.max(0,((all.size()-1)/8)*8));for(int i=offset;i<Math.min(offset+8,all.size());i++)list.add(all.get(i));rows=list;s.text(4,2,view+" | rows "+(offset+1)+"-"+(offset+rows.size())+" / "+all.size(),YELLOW);int i=0;for(var item:rows){String text=switch(view){case "POPULATIONS","RUNFORM"->item.path("count").asText()+" customers | seed "+item.path("seed").asText()+" | "+item.path("asOf").asText();case "NEW"->item.path("id").asText()+" "+item.path("data").path("name").asText();case "DRAFTS"->item.path("name").asText()+" v"+item.path("version").asText()+" / "+item.path("offer").path("product").asText();case "RUNS"->item.path("draft").path("name").asText()+" v"+item.path("draft").path("version").asText()+" "+item.path("status").asText()+" "+item.path("createdAt").asText();default->item.path("offerId").asText()+" "+item.path("publishedAt").asText();};s.text(6+i,2,(++i)+"  "+text,BLUE);}if(rows.isEmpty())s.text(7,3,"No records yet. F3 returns to the Business menu.",WHITE);if(view.equals("NEW")){s.field("name",16,15,60,"New offer experiment","Draft name");s.text(18,2,"Choose a baseline. Its first associated campaign is snapshotted.",WHITE);}if(view.equals("RUNFORM")){s.field("seed",16,25,19,"20260918","Model / partition seed");s.text(18,2,"Select a population; both offers use identical inputs and date.",WHITE);}s.field("choice",20,23,2,"","Select row");footer="ENTER=Select F7/F8=Page F3=Back";}
            case "DRAFT"->{s.text(5,2,draft.path("name").asText()+" | draft/rules v"+draft.path("version").asText(),CYAN);s.text(6,2,"Baseline "+draft.path("baseline").path("id").asText()+" v"+draft.path("baseline").path("version").asText()+" | "+draft.path("offer").path("product").asText(),BLUE);String[] labels={"Edit offer terms / dates","Edit Step 1 underwriting criteria","Edit Step 2 marketing criteria","Edit Step 3 bureau criteria","Run baseline / candidate simulation","Inspect complete draft snapshot"};for(int i=0;i<labels.length;i++)s.text(9+i,5,(i+1)+"  "+labels[i],BLUE);s.text(17,2,"Each save creates a version. Consent / opt-out / suppression are locked.",WHITE);s.field("choice",20,23,1,"","Select option");}
            case "EDIT"->{s.text(4,2,"Edit "+kind+" | page "+(page+1)+"/"+((keys.size()+7)/8)+" | source v"+draft.path("version").asText(),YELLOW);for(int i=page*8;i<Math.min(keys.size(),page*8+8);i++){String k=keys.get(i);var n=form.path(k);s.field(k,6+i-page*8,31,k.equals("name")?46:20,n.isBoolean()?n.asBoolean()?"Y":"N":n.asText(),label(k));}s.text(16,2,"Score: 0=disabled or 300-850. DTI: 999=unbounded demonstration cap.",WHITE);s.text(17,2,"Rates in percent; money in USD. Y/N fields are explicit.",WHITE);s.text(18,2,"Bureau identity matching, consent and suppression cannot be disabled.",CYAN);footer="ENTER="+(page<(keys.size()-1)/8?"Next page":"Save new version")+" F7/F8=Page F3=Cancel";}
            case "RUN"->{run=get("runs/"+runId);s.text(5,2,run.path("draft").path("name").asText()+" / v"+run.path("draft").path("version").asText()+" / "+run.path("status").asText(),CYAN);s.text(6,2,"Run: "+runId,BLUE);if(run.path("status").asText().equals("COMPLETED")){var all=run.path("report").path("overall");s.text(8,2,"Population "+all.path("population").asText()+" | Eligible baseline "+all.path("baseline").path("eligible").asText()+" -> candidate "+all.path("candidate").path("eligible").asText(),WHITE);s.text(9,2,"Newly eligible "+all.path("newlyEligible").asText()+" | Lost eligibility "+all.path("lostEligibility").asText(),WHITE);String[] labels={"Overall statistics / confidence intervals / rejection reasons","Held-out test statistics","Cohort comparison / impact analysis","Model quality / assumptions / limitations","Inspect per-customer eligibility and scores","Review and publish this tested offer + rules"};for(int i=0;i<labels.length;i++)s.text(11+i,3,(i+1)+"  "+labels[i],BLUE);s.text(18,2,"Fit is customer utility. Acceptance is simulated, never measured.",YELLOW);s.field("choice",20,23,1,"","Select report");}else{s.text(9,2,run.path("status").asText().equals("FAILED")?run.path("error").asText():"Running in the background. ENTER refreshes; F3 can leave safely.",WHITE);s.field("refresh",20,23,1,"","Refresh run");}}
            case "REPORT","ROW"->{s.text(4,2,section,YELLOW);for(int i=offset;i<Math.min(offset+13,reportLines.size());i++)s.text(6+i-offset,1,reportLines.get(i),WHITE);s.text(20,2,"Lines "+(offset+1)+"-"+Math.min(offset+13,reportLines.size())+" / "+reportLines.size(),BLUE);footer="F7/F8=More statistics F3=Back";}
            case "PEOPLE","ROWS"->{JsonNode all=view.equals("PEOPLE")?get("populations/"+populationId+"/customers?offset="+offset+"&limit=8").path("items"):get("runs/"+runId+"/rows?offset="+offset+"&limit=8");rows=all;s.text(4,2,view.equals("PEOPLE")?"Synthetic inputs (never active customers)":"Customer-level comparison: baseline -> candidate",YELLOW);int i=0;for(var row:rows){String text=view.equals("PEOPLE")?row.path("id").asText()+" Income "+row.path("customer").path("monthlyIncomeUsd").asText("unknown")+" self score "+row.path("customer").path("creditScore").asText()+" bureau "+row.path("bureau").path("creditScore").asText():row.path("customerId").asText()+" eligible "+row.path("analysis").path("baselineEligible").asText()+" -> "+row.path("analysis").path("candidateEligible").asText()+" cohort "+row.path("analysis").path("cohort").asText()+" "+row.path("analysis").path("partition").asText();s.text(6+i,2,(++i)+"  "+text,BLUE);}s.field("choice",20,23,1,"","Inspect row");footer="ENTER=Inspect F7/F8=Page F3=Back";}
            case "PUBLISH"->{s.text(5,2,"Publish tested draft v"+run.path("draft").path("version").asText()+" to the active local catalog",YELLOW);s.text(7,2,"Review eligibility losses, cohort sizes, fit, payment and cost changes.",WHITE);s.text(9,2,"A new campaign copy preserves existing offers and qualifications.",WHITE);s.text(11,2,"Global suppression, consent and dispatch rules remain mandatory.",CYAN);s.text(13,2,"No minimum fit uplift is imposed. This is your Business decision.",WHITE);s.field("note",16,15,60,"","Review note");s.field("confirm",19,28,1,"","Type P to publish");footer="ENTER=Publish reviewed version F3=Back without publishing";}
            case "RECEIPT"->{s.text(5,2,"Published with immutable rule versions",CYAN);int i=0;for(String k:List.of("offerId","campaignId","ruleVersion","publishedAt","reviewNote"))s.text(8+i++,2,k+": "+receipt.path(k).asText(),BLUE);s.text(16,2,"New Customer applications can qualify for this offer automatically.",WHITE);s.text(18,2,"Existing catalog offers and models retain their versions.",WHITE);s.field("choice",20,23,1,"","Business menu");}
        }if(!notice.isBlank())s.text(19,1,notice,CYAN);return footer;
    }
    /** Converts a configuration field name into a readable terminal label. */
    private static String label(String key){return switch(key){case "minimumScore"->"Minimum credit score";case "minimumIncomeUsd"->"Min monthly income USD";case "maximumDtiPct"->"Max debt / income %";case "maximumUtilizationPct"->"Max utilization %";case "maximumDelinquencies"->"Max delinquencies (12 mo)";case "maximumAmountUsd"->"Maximum amount USD";case "minimumAmountUsd"->"Minimum amount USD";case "incomeMultiple"->"Max amount / monthly income";case "maximumLtvPct"->"Max loan / vehicle value %";case "maximumVehicleAge"->"Max vehicle age (years)";case "minimumTenureMonths"->"Min banking tenure (months)";case "excludeExistingProduct"->"Exclude product held Y/N";case "maximumInquiries"->"Max inquiries (6 months)";case "minimumHistoryMonths"->"Min credit history months";case "maximumReportAgeDays"->"Max bureau report age days";case "allowBankruptcy"->"Allow bankruptcy Y/N";case "illustrativeAprPct"->"APR %";case "annualFeeUsd"->"Annual fee USD";case "termMonths"->"Term months (card=0)";case "startsOn"->"Start date YYYY-MM-DD";case "endsOn"->"End date YYYY-MM-DD";case "active"->"Active Y/N";default->key;};}
}
